Repository tlcsdm/javafx-swt, pull requests merged in 2023-11, with the labels that each got.

#9 build: Update lock.yml
  .github/workflows/lock.yml
Labels: size/XS

#10 build: Update .gitignore
  .gitignore
Labels: size/XS

#11 docs: Update README.md
  README.md
Labels: size/XS

#12 build: Modify pom
  .gitignore
  pom.xml
  src/main/java/module-info.java
Labels: size/M

#13 build: Modify modules
  pom.xml
  src/main/java/module-info.java
Labels: size/S

#14 build: Modify build
  pom.xml
Labels: size/XS

#15 build: Modify open
  pom.xml
Labels: size/XS

#16 build: Modify module
  pom.xml
Labels: size/XS

#19 build: Add help plugin
  pom.xml
Labels: size/XS

#20 build: Modify pom
  pom.xml
Labels: size/M

#21 build: Modify pom
  pom.xml
Labels: size/S

#23 build: Update pom.xml
  pom.xml
Labels: size/XS

#24 build: Update maven.yml
  .github/workflows/maven.yml
Labels: size/XS

#25 build: Update pom.xml
  pom.xml
Labels: size/XS
